name: staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: staging-and-prod
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-staging:
    uses: ./.github/workflows/2-deploy.yaml
    secrets: inherit
    with:
      stage: staging

  create-release-pr:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release PR
        uses: decewei/deploy-tools/actions/create-release-pr@release
        with:
          app-id: ${{ vars.ACTION_BOT_APP_ID }}
          private-key: ${{ secrets.ACTION_BOT_PRIVATE_KEY }}
          source-branch: 'main'
          target-branch: 'release'
          review-team: ''
          label: 'release:required-approval'
